name: Lint, format and test lambdas
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lambdas/**"
      - ".github/workflows/**"  

jobs:
  lambdas-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lambda:
          - ip-geolocation
          - loader
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dev dependencies
        working-directory: lambdas
        run: pip3 install --user -r dev_requirements.txt

      - name: Install lambda dependencies
        working-directory: lambdas/${{ matrix.lambda }}
        run: make install

      - name: Lint
        working-directory: lambdas/${{ matrix.lambda }}
        run: make lint

      - name: Format
        working-directory: lambdas/${{ matrix.lambda }}
        run: make ARGS=--check fmt

      - name: Test
        working-directory: lambdas/${{ matrix.lambda }}
        run: make test       